<?php

return [
    'items' => [
        [
            'name_bn' => 'বাংলাদেশ',
            'name_en' => 'Bangladesh',
            'slug' => 'bangladesh',
            'meta_description' => 'বাংলাদেশের সর্বশেষ জাতীয় খবর, রাজনীতি, রাজধানী, অপরাধ, দুর্ঘটনা ও আইন-বিচার বিষয়ক নির্ভরযোগ্য সংবাদ পড়ুন Dhaka Magazine-এ।',
            'children' => [
                ['name_bn' => 'জাতীয়', 'name_en' => 'National', 'slug' => 'national', 'meta_description' => 'জাতীয় গুরুত্বপূর্ণ ঘটনা, নীতি, প্রশাসন ও জনজীবনের প্রভাবশালী খবর নির্ভরযোগ্যভাবে পড়ুন Dhaka Magazine-এর জাতীয় সংবাদে।'],
                ['name_bn' => 'রাজধানী', 'name_en' => 'Dhaka', 'slug' => 'dhaka', 'meta_description' => 'ঢাকার যানজট, উন্নয়ন, নাগরিক সেবা, অপরাধ ও জনজীবনের সর্বশেষ খবর জানতে পড়ুন Dhaka Magazine-এর রাজধানী সংবাদ।'],
                ['name_bn' => 'অপরাধ', 'name_en' => 'Crime', 'slug' => 'crime', 'meta_description' => 'দেশের অপরাধ, আইনশৃঙ্খলা, তদন্ত ও নিরাপত্তা পরিস্থিতির গুরুত্বপূর্ণ আপডেট নির্ভরযোগ্যভাবে তুলে ধরে Dhaka Magazine।'],
                ['name_bn' => 'দুর্ঘটনা', 'name_en' => 'Accidents', 'slug' => 'accidents', 'meta_description' => 'সড়ক, নৌ, অগ্নিকাণ্ডসহ বিভিন্ন দুর্ঘটনার সর্বশেষ তথ্য, উদ্ধার তৎপরতা ও সতর্কতার খবর পড়ুন Dhaka Magazine-এ।'],
                ['name_bn' => 'আইন-বিচার', 'name_en' => 'Law Justice', 'slug' => 'law-justice', 'meta_description' => 'আদালত, মামলা, রায়, আইন ও বিচার ব্যবস্থার গুরুত্বপূর্ণ সংবাদ সহজ ভাষায় জানতে পড়ুন Dhaka Magazine-এর আইন-বিচার বিভাগ।'],
                ['name_bn' => 'রাজনীতি', 'name_en' => 'Politics', 'slug' => 'politics', 'meta_description' => 'বাংলাদেশের রাজনীতি, দলীয় কর্মসূচি, নির্বাচন, সংসদ ও নীতিনির্ধারণী খবর বিশ্লেষণসহ পড়ুন Dhaka Magazine-এ।'],
            ],
        ],
        [
            'name_bn' => 'অর্থনীতি',
            'name_en' => 'Economy',
            'slug' => 'economy',
            'meta_description' => 'দেশের অর্থনীতি, বাজার, ব্যাংক, শেয়ারবাজার, শিল্প ও কৃষির সর্বশেষ সংবাদ এবং বিশ্লেষণ পড়ুন Dhaka Magazine-এ।',
            'children' => [
                ['name_bn' => 'শেয়ারবাজার', 'name_en' => 'Stock Market', 'slug' => 'stock-market', 'meta_description' => 'শেয়ারবাজারের সূচক, লেনদেন, কোম্পানি খবর, বিনিয়োগ পরিবেশ ও বাজার বিশ্লেষণের নির্ভরযোগ্য আপডেট পড়ুন Dhaka Magazine-এ।'],
                ['name_bn' => 'ব্যাংকিং ও বীমা', 'name_en' => 'Banking Insurance', 'slug' => 'banking-insurance', 'meta_description' => 'ব্যাংকিং, বীমা, ঋণ, আমানত, আর্থিক নীতি ও খাতভিত্তিক গুরুত্বপূর্ণ খবর জানতে পড়ুন Dhaka Magazine।'],
                ['name_bn' => 'শিল্প', 'name_en' => 'Industry', 'slug' => 'industry', 'meta_description' => 'দেশের শিল্পখাত, উৎপাদন, রপ্তানি, বিনিয়োগ ও উদ্যোক্তা কার্যক্রমের সর্বশেষ সংবাদ তুলে ধরে Dhaka Magazine।'],
                ['name_bn' => 'কৃষি', 'name_en' => 'Agriculture', 'slug' => 'agriculture', 'meta_description' => 'কৃষি, ফসল, বাজারদর, কৃষক, প্রযুক্তি ও নীতিসহ কৃষিখাতের প্রয়োজনীয় সংবাদ পড়ুন Dhaka Magazine-এ।'],
            ],
        ],
        ['name_bn' => 'আন্তর্জাতিক', 'name_en' => 'World', 'slug' => 'world', 'meta_description' => 'বিশ্ব রাজনীতি, সংঘাত, কূটনীতি, অর্থনীতি ও আন্তর্জাতিক ঘটনাপ্রবাহের গুরুত্বপূর্ণ খবর নির্ভরযোগ্যভাবে পড়ুন Dhaka Magazine-এ।', 'children' => []],
        [
            'name_bn' => 'সারাদেশ',
            'name_en' => 'Country News',
            'slug' => 'country-news',
            'meta_title' => 'সারাদেশ সংবাদ | Dhaka Magazine',
            'meta_description' => 'দেশের বিভিন্ন জেলা ও অঞ্চলের সর্বশেষ খবর, ঘটনা, জনজীবন ও স্থানীয় আপডেট পড়ুন Dhaka Magazine-এ।',
            'children' => [],
        ],
        ['name_bn' => 'বিনোদন', 'name_en' => 'Entertainment', 'slug' => 'entertainment', 'meta_description' => 'সিনেমা, নাটক, গান, তারকা, ওটিটি ও সংস্কৃতি অঙ্গনের নতুন খবর ও আলোচিত ঘটনা পড়ুন Dhaka Magazine বিনোদনে।', 'children' => []],
        [
            'name_bn' => 'খেলাধুলা',
            'name_en' => 'Sports',
            'slug' => 'sports',
            'meta_description' => 'ক্রিকেট, ফুটবল ও অন্যান্য খেলার স্কোর, ম্যাচ, খেলোয়াড় ও টুর্নামেন্টের সর্বশেষ খবর পড়ুন Dhaka Magazine খেলাধুলায়।',
            'children' => [
                ['name_bn' => 'ফুটবল', 'name_en' => 'Football', 'slug' => 'football', 'meta_description' => 'দেশি-বিদেশি ফুটবল, ক্লাব, জাতীয় দল, ম্যাচ ফল, খেলোয়াড় ও টুর্নামেন্টের খবর পড়ুন Dhaka Magazine-এ।'],
                ['name_bn' => 'ক্রিকেট', 'name_en' => 'Cricket', 'slug' => 'cricket', 'meta_description' => 'বাংলাদেশ ও বিশ্ব ক্রিকেটের ম্যাচ, স্কোর, সিরিজ, দল, খেলোয়াড় ও বিশ্লেষণধর্মী খবর পড়ুন Dhaka Magazine-এ।'],
                ['name_bn' => 'অন্যান্য খেলা', 'name_en' => 'Other Sports', 'slug' => 'other-sports', 'meta_description' => 'টেনিস, অ্যাথলেটিকস, অলিম্পিকসহ অন্যান্য খেলার গুরুত্বপূর্ণ খবর ও ফলাফল জানতে পড়ুন Dhaka Magazine।'],
            ],
        ],
        [
            'name_bn' => 'চাকরি',
            'name_en' => 'Jobs',
            'slug' => 'jobs',
            'meta_description' => 'সরকারি ও বেসরকারি চাকরির নিয়োগ বিজ্ঞপ্তি, আবেদন প্রক্রিয়া, পরীক্ষার খবর ও ক্যারিয়ার আপডেট পড়ুন Dhaka Magazine-এ।',
            'children' => [
                ['name_bn' => 'সরকারি চাকরি', 'name_en' => 'Government Jobs', 'slug' => 'government-jobs', 'meta_description' => 'সরকারি চাকরির নিয়োগ বিজ্ঞপ্তি, আবেদন সময়সূচি, পরীক্ষা, ফলাফল ও প্রস্তুতির প্রয়োজনীয় খবর পড়ুন Dhaka Magazine-এ।'],
                ['name_bn' => 'বেসরকারি চাকরি', 'name_en' => 'Private Jobs', 'slug' => 'private-jobs', 'meta_description' => 'বেসরকারি চাকরি, করপোরেট নিয়োগ, এনজিও, ব্যাংক ও ক্যারিয়ার সুযোগের আপডেট জানতে পড়ুন Dhaka Magazine।'],
            ],
        ],
        [
            'name_bn' => 'জীবনযাপন',
            'name_en' => 'Lifestyle',
            'slug' => 'lifestyle',
            'meta_description' => 'স্বাস্থ্য, রূপচর্চা, খাবার, পরিবার ও দৈনন্দিন জীবনযাপনের উপকারী পরামর্শ ও খবর পড়ুন Dhaka Magazine-এ।',
            'children' => [
                ['name_bn' => 'স্বাস্থ্য', 'name_en' => 'Health', 'slug' => 'health', 'meta_description' => 'স্বাস্থ্য, চিকিৎসা, রোগ প্রতিরোধ, পুষ্টি ও সুস্থ জীবনযাপনের প্রয়োজনীয় খবর ও পরামর্শ পড়ুন Dhaka Magazine-এ।'],
                ['name_bn' => 'রূপচর্চা', 'name_en' => 'Beauty', 'slug' => 'beauty', 'meta_description' => 'ত্বক, চুল, সৌন্দর্যচর্চা ও ব্যক্তিগত যত্নের সহজ পরামর্শ এবং নতুন ট্রেন্ড জানতে পড়ুন Dhaka Magazine।'],
                ['name_bn' => 'খাবার', 'name_en' => 'Recipes', 'slug' => 'recipes', 'meta_description' => 'রেসিপি, খাবারদাবার, পুষ্টি, রান্নার কৌশল ও খাদ্যাভ্যাসের আকর্ষণীয় লেখা পড়ুন Dhaka Magazine জীবনযাপনে।'],
            ],
        ],
        ['name_bn' => 'ভিডিও', 'name_en' => 'Videos', 'slug' => 'videos', 'meta_description' => 'দেশ-বিদেশ, বিনোদন, খেলাধুলা ও বিশেষ ঘটনার নির্বাচিত ভিডিও সংবাদ ও প্রতিবেদন দেখুন Dhaka Magazine ভিডিও বিভাগে।', 'children' => []],
        [
            'name_bn' => 'বিশেষ',
            'name_en' => 'Special',
            'slug' => 'dhaka-magazine-special',
            'meta_title' => 'বিশেষ প্রতিবেদন | Dhaka Magazine',
            'meta_description' => 'গুরুত্বপূর্ণ ঘটনা, বিশেষ প্রতিবেদন, বিশ্লেষণ ও অনুসন্ধানধর্মী সংবাদ পড়ুন Dhaka Magazine-এ।',
            'children' => [],
        ],
        [
            'name_bn' => 'অন্যান্য',
            'name_en' => 'Others News',
            'slug' => 'others-news',
            'meta_description' => 'ধর্ম, প্রযুক্তি, শিক্ষা, প্রবাসসহ নানা বিষয়ের গুরুত্বপূর্ণ ও প্রয়োজনীয় খবর একসঙ্গে পড়ুন Dhaka Magazine অন্যান্য বিভাগে।',
            'children' => [
                ['name_bn' => 'ধর্ম', 'name_en' => 'Religion', 'slug' => 'religion', 'meta_description' => 'ধর্মীয় আলোচনা, উৎসব, আচার, সমাজ ও মূল্যবোধ সম্পর্কিত প্রয়োজনীয় খবর ও লেখা পড়ুন Dhaka Magazine-এ।'],
                ['name_bn' => 'তথ্য-প্রযুক্তি', 'name_en' => 'Technology', 'slug' => 'technology', 'meta_description' => 'প্রযুক্তি, গ্যাজেট, স্টার্টআপ, ইন্টারনেট, এআই ও ডিজিটাল জীবনের সর্বশেষ খবর পড়ুন Dhaka Magazine-এ।'],
                ['name_bn' => 'শিক্ষা', 'name_en' => 'Education', 'slug' => 'education', 'meta_description' => 'শিক্ষা প্রতিষ্ঠান, পরীক্ষা, ভর্তি, ফলাফল, নীতি ও শিক্ষার্থীদের প্রয়োজনীয় খবর জানতে পড়ুন Dhaka Magazine।'],
                ['name_bn' => 'মতামত', 'name_en' => 'Opinion', 'slug' => 'opinion', 'meta_title' => 'মতামত | Dhaka Magazine', 'meta_description' => 'দেশ, রাজনীতি, সমাজ ও সমসাময়িক বিষয় নিয়ে বিশ্লেষণধর্মী মতামত পড়ুন Dhaka Magazine-এ।'],
                ['name_bn' => 'প্রবাস', 'name_en' => 'Expatriates', 'slug' => 'expatriates', 'meta_description' => 'প্রবাসী বাংলাদেশি, শ্রমবাজার, রেমিট্যান্স, ভিসা ও বিদেশে জীবনযাপনের খবর পড়ুন Dhaka Magazine প্রবাস বিভাগে।'],
            ],
        ],
    ],

    'redirects' => [
        'জাতীয়' => 'bangladesh/national',
        'রাজধানী' => 'bangladesh/dhaka',
        'অপরাধ' => 'bangladesh/crime',
        'দুর্ঘটনা' => 'bangladesh/accidents',
        'আইন-বিচার' => 'bangladesh/law-justice',
        'রাজনীতি' => 'bangladesh/politics',
        'শেয়ারবাজার' => 'economy/stock-market',
        'ব্যাংকিং' => 'economy/banking-insurance',
        'ব্যাংকিং-ও-বীমা' => 'economy/banking-insurance',
        'শিল্প' => 'economy/industry',
        'কৃষি' => 'economy/agriculture',
        'বিশ্ব' => 'world',
        'খেলা' => 'sports',
        'ফুটবল' => 'sports/football',
        'ক্রিকেট' => 'sports/cricket',
        'অন্যান্য' => 'others-news',
        'সরকারি-চাকরি' => 'jobs/government-jobs',
        'বেসরকারি-চাকরি' => 'jobs/private-jobs',
        'লাইফস্টাইল' => 'lifestyle',
        'স্বাস্থ্য' => 'lifestyle/health',
        'রূপচর্চা' => 'lifestyle/beauty',
        'খাবার' => 'lifestyle/recipes',
        'ভিডিও' => 'videos',
        'ধর্ম' => 'others-news/religion',
        'তথ্য-প্রযুক্তি' => 'others-news/technology',
        'প্রযুক্তি' => 'others-news/technology',
        'শিক্ষা' => 'others-news/education',
        'মতামত' => 'others-news/opinion',
        'প্রবাস' => 'others-news/expatriates',
        'country' => 'bangladesh',
        'সারাদেশ' => 'country-news',
        'বিশেষ' => 'dhaka-magazine-special',
        'বিশেষ-প্রতিবেদন' => 'dhaka-magazine-special',
    ],
];
